# Generated by Django 4.0.6 on 2022-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('data', models.DateField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
